Berlin style fixes
flathub/website pull request #486
Opened 2022-07-24 13:44 UTC by jimmac

Couple of papercuts on the stylesheet we found during the Berlin GUADEC

2022-07-24 15:53 UTC, razzeee commented
I don't think we want the font part. The next.js docs seem clear how they like fonts to be included https://nextjs.org/docs/basic-features/font-optimization even if we're not using a google font.

2022-07-28 16:40 UTC, jimmac commented
I understand it's part of the framework, but it's really stepping all over the founding stones of web design. Moving CSS properties into classes, making fonts only work with javascript.</rant>

I'll separate the font issue.

2022-07-28 16:47 UTC, razzeee commented
I'm not sure if that's true, the ssr/static site generation might still
render it fine.

Jakub Steiner ***@***.***> schrieb am Do., 28. Juli 2022,
18:40:

> I understand it's part of the framework, but it's really stepping all over
> the founding stones of web design. Moving CSS properties into classes,
> making fonts only work with javascript.
>
> I'll separate the font issue.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/flathub/website/pull/486#issuecomment-1198386199>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNLEZG5KGVUDDGDQHRAGW3VWKZZJANCNFSM54PWDHGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-07-29 09:45 UTC, barthalion commented
I've looked into font optimization and it just doesn't work at all unless you're using Google Fonts. I'd say let's do whatever works given Next.js stance on it.

2022-07-29 09:57 UTC, razzeee commented
yeah, let's just do css fonts for now, as it's unclear, when they will correctly support different font providers. The current implementation probably was due to us hoping it would be soon and then just would work. That's probably not going to happen, as far as I read.

2022-07-29 09:58 UTC, razzeee commented on frontend/pages/index.tsx
> -              src="/assets/landing.svg"
Probably want to delete the svg too then?

2022-07-29 10:01 UTC, razzeee requested changes
Just one minor deletion missing

2022-07-30 18:33 UTC, razzeee approved these changes

2022-07-30 18:39 UTC, merged